### ISSUE TITLE
ReferenceError: 'Uint8Array' is undefined  - IE 9

### ISSUE THREAD

**Issue by swanidhi** [eligrey/Blob.js#41]
I got this error while trying to use it on IE 9 for a download file functionality.

ReferenceError: 'Uint8Array' is undefined

**Comment by Ashot72** [comment]
I am getting the same error on IE 9

**Comment by zky829** [comment]
I'm using this polyfill as a solution: https://github.com/inexorabletash/polyfill/blob/master/typedarray.js

**Comment by swanidhi** [comment]
That did take off that error from the console. But then I got this
``code Error: The data area passed to a system call is too small.``

**Comment by donwan** [comment]
I think the problem is that IE9 doesn't even like it if you test for existence using type (line 192).  I changed both occurrences of "if (UintBArray && ..." to "if (typeof UnitBArray != 'undefined' && ..." and was able to get through it.  Blob.js had "else" clauses for the case where UintBArray didn't exist, it's just that IE9 stopped before getting there.

**Comment by SamuelDivinium** [comment]
Hello guys, I have a similar problem with this plugin. 
I have to make Blob work on IE9 too, and when I want to use this plugin I get the same undefined error. I tried the mentioned "typedarray" plugin but it throws this error (when used with the Blob.js):
"Unable to get value of the property 'slice': object is null or undefined" (line 171 character 4)
It seems the "FakeBlob" wants to slice my data but the start and end variables are both undefined. Which makes me assume that the Blob.js can't read properly the unofficial uint8array conversion (because in debug mode the uint8array object seems good before I try to make a blob from it).

Any ideas about this error? Thanks in advance!

**Comment by chandramuralis** [comment]
@donwan  Submitted a [Pull Request #48 ](https://github.com/eligrey/Blob.js/pull/48) for this issue. Might still require typedarray [polyfill](https://github.com/inexorabletash/polyfill) for fixing this issue

**Comment by roger2hk** [comment]
The error goes away after adding the polyfill in IE 9 but the download functionality is still not working. For details, please refer to https://github.com/eligrey/Blob.js/pull/48.

This issue should be closed.

**Comment by eligrey** [comment]
@roger2hk got it. thanks
